sudo: required

language: go
go:
  - "1.11.x"

services:
  - docker

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - make docker.build docker.test-report
  - make docker WHAT="make lint"
  - make test-new

after_success:
  - go get github.com/mattn/goveralls; $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
